{
 "title": "Pizza Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "New Panel",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{component=\"jwt-pizza-service\"} |= `` | json"
    }
   ]
  },
  {
   "title": "Active users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "userbase_count{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Authentications",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "targets": [
    {
     "expr": "rate(auth_success{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Success"
    },
    {
     "expr": "rate(auth_fail{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Fail"
    }
   ]
  },
  {
   "title": "HTTP requests/minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(request_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "TOTAL"
    },
    {
     "expr": "rate(request_get{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "GET"
    },
    {
     "expr": "rate(request_post{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "POST"
    },
    {
     "expr": "rate(request_delete{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "DELETE"
    },
    {
     "expr": "rate(request_put{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "PUT"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_memory{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "system_cpu{source=\"jwt-pizza-service\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "system_request{source=\"jwt-pizza-service\"}",
     "legendFormat": "Request latency"
    }
   ]
  },
  {
   "title": "Pizza purchases",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(pizza_sold{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Pizza purchases"
    },
    {
     "expr": "rate(pizza_fail{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Pizza failures"
    }
   ]
  },
  {
   "title": "revenue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "currencyBTC" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(pizza_cash{method=\"cash\", source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pizza latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "system_pizza{source=\"jwt-pizza-service\"}",
     "legendFormat": "Pizza latency"
    }
   ]
  }
 ]
}